# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_lipsbodypose', [dirname(__file__)])
        except ImportError:
            import _lipsbodypose
            return _lipsbodypose
        if fp is not None:
            try:
                _mod = imp.load_module('_lipsbodypose', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _lipsbodypose = swig_import_helper()
    del swig_import_helper
else:
    import _lipsbodypose
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Frame(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Frame, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Frame, name)
    __repr__ = _swig_repr

    def __init__(self, pMatRGB, pMatDepth, pSkeleton):
        this = _lipsbodypose.new_Frame(pMatRGB, pMatDepth, pSkeleton)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["pMatRGB"] = _lipsbodypose.Frame_pMatRGB_set
    __swig_getmethods__["pMatRGB"] = _lipsbodypose.Frame_pMatRGB_get
    if _newclass:
        pMatRGB = _swig_property(_lipsbodypose.Frame_pMatRGB_get, _lipsbodypose.Frame_pMatRGB_set)
    __swig_setmethods__["pMatDepth"] = _lipsbodypose.Frame_pMatDepth_set
    __swig_getmethods__["pMatDepth"] = _lipsbodypose.Frame_pMatDepth_get
    if _newclass:
        pMatDepth = _swig_property(_lipsbodypose.Frame_pMatDepth_get, _lipsbodypose.Frame_pMatDepth_set)
    __swig_setmethods__["pSkeleton"] = _lipsbodypose.Frame_pSkeleton_set
    __swig_getmethods__["pSkeleton"] = _lipsbodypose.Frame_pSkeleton_get
    if _newclass:
        pSkeleton = _swig_property(_lipsbodypose.Frame_pSkeleton_get, _lipsbodypose.Frame_pSkeleton_set)
    __swig_destroy__ = _lipsbodypose.delete_Frame
    __del__ = lambda self: None
Frame_swigregister = _lipsbodypose.Frame_swigregister
Frame_swigregister(Frame)

class lipsbodypose(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, lipsbodypose, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, lipsbodypose, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _lipsbodypose.new_lipsbodypose()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _lipsbodypose.delete_lipsbodypose
    __del__ = lambda self: None

    def readFrame(self):
        return _lipsbodypose.lipsbodypose_readFrame(self)

    def getLibVersion(self):
        return _lipsbodypose.lipsbodypose_getLibVersion(self)

    def switchSourceType(self):
        return _lipsbodypose.lipsbodypose_switchSourceType(self)
lipsbodypose_swigregister = _lipsbodypose.lipsbodypose_swigregister
lipsbodypose_swigregister(lipsbodypose)

# This file is compatible with both classic and new-style classes.


